#!/usr/bin/env bash
#
# Vendor the tutorials into the site (Option A: prose is canonical in each app repo).
#
# For every entry in tutorials.toml this script:
#   1. fetches the canonical TUTORIAL.md — a sibling checkout if present
#      (../<slug>/TUTORIAL.md), otherwise the raw file from GitHub,
#   2. strips the leading H1 (the docs theme renders <h1>{{ page.title }}</h1>),
#   3. wraps it with TOML front matter, an above-the-fold demo/pull line, and the
#      mandatory footer (repo · demo · GHCR · issues),
#   4. writes content/tutorials/<slug>.md, and
#   5. regenerates the sidebar nav partial.
#
# Nothing here is edited by hand: content/tutorials/*.md and the nav partial are
# derived artifacts (see .gitignore).

set -euo pipefail

cd "$(dirname "$0")/.."

MANIFEST="tutorials.toml"
OUT_DIR="content/tutorials"
NAV_PARTIAL="templates/partials/tutorial-nav.html"

mkdir -p "$OUT_DIR" "$(dirname "$NAV_PARTIAL")"

# --- parse the manifest into tab-separated records, sorted by weight ----------
records="$(
  awk '
    function flush() {
      if (slug != "")
        printf "%s\t%s\t%s\t%s\t%s\t%s\n", slug, title, weight, repo, demo, ghcr
      slug=""; title=""; weight=""; repo=""; demo=""; ghcr=""
    }
    /^[[:space:]]*#/          { next }
    /^\[\[tutorial\]\]/       { flush(); next }
    /^[[:space:]]*(slug|title|weight|repo|demo|ghcr)[[:space:]]*=/ {
      key=$1
      val=$0; sub(/^[^=]*=[[:space:]]*/, "", val); gsub(/^"|"$/, "", val)
      if      (key=="slug")   slug=val
      else if (key=="title")  title=val
      else if (key=="weight") weight=val
      else if (key=="repo")   repo=val
      else if (key=="demo")   demo=val
      else if (key=="ghcr")   ghcr=val
    }
    END { flush() }
  ' "$MANIFEST" | sort -t"$(printf '\t')" -k3,3n
)"

if [ -z "$records" ]; then
  echo "vendor: no tutorials in $MANIFEST — nothing to do" >&2
  exit 0
fi

# --- (re)generate the nav partial header -------------------------------------
{
  echo "{# generated by scripts/vendor.sh — do not edit #}"
} > "$NAV_PARTIAL"

count=0
while IFS="$(printf '\t')" read -r slug title weight repo demo ghcr; do
  [ -n "$slug" ] || continue

  # 1. locate the canonical prose: sibling checkout first, raw GitHub fallback
  sibling="../$slug/TUTORIAL.md"
  raw_body="$(mktemp)"
  if [ -f "$sibling" ]; then
    echo "vendor: $slug ← $sibling"
    cat "$sibling" > "$raw_body"
  else
    raw_url="${repo/github.com/raw.githubusercontent.com}/main/TUTORIAL.md"
    echo "vendor: $slug ← $raw_url"
    if ! curl -fsSL "$raw_url" -o "$raw_body"; then
      echo "vendor: WARNING could not fetch $slug ($raw_url) — skipping" >&2
      rm -f "$raw_body"
      continue
    fi
  fi

  # 2. strip the first top-level H1 (theme renders the title itself)
  body="$(mktemp)"
  awk 'BEGIN{done=0} done==0 && /^# /{done=1; next} {print}' "$raw_body" > "$body"
  rm -f "$raw_body"

  # 3. + 4. wrap with front matter, above-the-fold line, and footer
  out="$OUT_DIR/$slug.md"
  {
    printf '+++\n'
    printf 'title = "%s"\n' "$title"
    printf 'weight = %s\n' "$weight"
    printf '+++\n\n'
    printf '> 🚀 **[Live demo](%s)** · 🐳 `docker pull %s:latest`\n\n' "$demo" "$ghcr"
    cat "$body"
    printf '\n---\n\n'
    printf '## Get it · run it · contribute\n\n'
    printf -- '- 📦 **Source:** [%s](%s)\n' "$repo" "$repo"
    printf -- '- 🚀 **Live demo:** [%s](%s)\n' "$demo" "$demo"
    printf -- '- 🐳 **Pull the image:** `docker pull %s:latest`\n' "$ghcr"
    printf -- '- 💬 **Contribute:** found a bug or want to help? [Open an issue](%s/issues) — contributions welcome.\n' "$repo"
  } > "$out"
  rm -f "$body"

  # 5. append the nav entry
  printf '<li><a href="{{ base_url }}/tutorials/%s/">%s</a></li>\n' "$slug" "$title" >> "$NAV_PARTIAL"

  count=$((count + 1))
done <<< "$records"

echo "vendor: wrote $count tutorial(s) → $OUT_DIR and $NAV_PARTIAL"
